apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-agent
  labels:
        type: stateful-service-ctmag-srv
spec:
    serviceName: ctmag
    selector:
        matchLabels:
            type: stateful-service-ctmag-srv
    replicas: 1 # number of running agents
    template:
        metadata:
            labels:
                type: stateful-service-ctmag-srv
        spec:
          containers:
          - name: ctmagent-container
            # container in ECR
            image: divand/controlmgentstatefullset:v2
            env:
            - name: PERSISTENT_VOL
              value: "/data/controlm/files"
            - name: CTM_SERVER_NAME
              # update value to your Control-M/Server name
              value: "192.168.126.5"
            - name: CTM_AGPORT
              value: "8443"
            - name: AAPI_END_POINT
              # update value to your AAPI end point
              value: "192.168.126.5"
            - name: AAPI_USER
              # update value to your EM user
              value: "emuser"
              # user's password, will be present in the logs! consider using k8s secret
            - name: AAPI_PASS
              value: "controlm"
            imagePullPolicy: Always
            ports:
            - containerPort: 8443
            volumeMounts:
              - name: pv-data
                mountPath: /data/controlm/files
          terminationGracePeriodSeconds: 10
    #      This sample is pulling the container from ECR. DockerHub is using imagePullSecret
    #      imagePullSecrets:
    #      - name: regcred
    #     See example_RBC.yaml for sample RBC Configuration
    #     serviceAccountName: statefulset-agent
          securityContext:
             # the agent account gid so it will be able to access the PV
             fsGroup: 1000
          volumes:
            - name: pv-data
              persistentVolumeClaim:
                claimName: pvc-controlm
